forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("register/", include("register.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("", TemplateView.as_view(template_name="base.html"), name="home_page"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_create_view, post_list_view, post_update_view, post_delete_view, PostLikeView, post_detail_view, \
    add_comment_view, category_list_view, posts_by_category_view

app_name = "posts"

urlpatterns = [
    path("",post_list_view,name="list"),
    path("add/",post_create_view,name="add"),
    path("<int:pk>/",post_detail_view,name="detail"),
    path("<int:pk>/edit/",post_update_view,name="edit"),
    path("<int:pk>/delete/",post_delete_view,name="delete"),
    path("<int:pk>/post_like/",PostLikeView,name="like"),
    path("<int:pk>/add_comment/",add_comment_view,name="add_comment"),
]

urlpatterns += [
    path("categories/", category_list_view, name="categories"),
    path("categories/<int:category_id>/", posts_by_category_view, name="posts_by_category"),
]

register/urls.py
from django.urls import path
from .views import signup_view

app_name = "register"

urlpatterns = [
    path("",signup_view,name="register")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BASE HTML{% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'forum/css/style.css' %}">
    {% block stylesheets %}{% endblock %}
</head>
<body>
    <nav>
      <ul>
        <li><h2 class="logo">FORUM</h2></li>
        <li><a href="{% url 'posts:list' %}">Home</a></li>
        <li><a href="{% url 'posts:categories' %}">Categories</a></li>
      </ul>
      <div>
        {% if user.is_authenticated %}
          <a href="{% url 'posts:add' %}">New Post</a>
          <a href="{% url 'user_profile' %}">Profile</a>
          <form action="{% url 'logout' %}" method="POST" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-link logout-btn">Logout</button>
          </form>
        {% else %}
          <a href="{% url 'register:register' %}">Sign-up</a>
          <a href="{% url 'login' %}">Login</a>
        {% endif %}
      </div>
    </nav>


    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    {% block additional_scripts %}{% endblock %}
</body>
</html>