forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("register/", include("register.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("", TemplateView.as_view(template_name="base.html"), name="home_page"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_create_view, post_list_view, post_update_view, post_delete_view, PostLikeView, post_detail_view, \
    add_comment_view, category_list_view, posts_by_category_view

app_name = "posts"

urlpatterns = [
    path("",post_list_view,name="list"),
    path("add/",post_create_view,name="add"),
    path("<int:pk>/",post_detail_view,name="detail"),
    path("<int:pk>/edit/",post_update_view,name="edit"),
    path("<int:pk>/delete/",post_delete_view,name="delete"),
    path("<int:pk>/post_like/",PostLikeView,name="like"),
    path("<int:pk>/add_comment/",add_comment_view,name="add_comment"),
]

urlpatterns += [
    path("categories/", category_list_view, name="categories"),
    path("categories/<int:category_id>/", posts_by_category_view, name="posts_by_category"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tmce_modeles

class PostCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    contents = tmce_modeles.HTMLField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(PostCategory,on_delete=models.SET_NULL,null=True)
    likes = models.ManyToManyField(User,related_name="post_likes")

    def number_of_likes(self):
        return self.likes.count()


class PostComment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    contents = models.TextField(max_length=255)
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)

posts/forms.py
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from .models import PostComment


class PostCommentForm(ModelForm):

    class Meta:
        model = PostComment
        fields = ["contents"]

    def __int__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "POST"

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.forms import BaseForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from .models import PostCategory

from .forms import PostCommentForm
from .models import Post, PostComment


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    fields = ['title', 'contents', 'category']
    success_url = reverse_lazy("posts:list")
    success_message = "Post został dodany!"

    def form_valid(self, form: BaseForm) -> HttpResponse:
        form.instance.user = self.request.user
        return super().form_valid(form)


post_create_view = PostCreateView.as_view()


from django.db.models import Count, Q

class PostListView(ListView):
    model = Post
    paginate_by = 5
    template_name = "posts/post_list.html"
    context_object_name = "object_list"

    def get_queryset(self):
        queryset = Post.objects.select_related('user', 'category').prefetch_related('likes').order_by("-created_datetime")
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) |
                Q(contents__icontains=search_query) |
                Q(category__name__icontains=search_query) |
                Q(user__username__icontains=search_query)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_liked_posts'] = Post.objects.annotate(like_count=Count('likes')) \
            .order_by('-like_count')[:5]
        context['search_query'] = self.request.GET.get('q', '')
        return context

post_list_view = PostListView.as_view()


class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Post
    fields = ['title', 'contents', 'category']
    template_name = "posts/post_update.html"
    success_url = reverse_lazy("posts:list")
    success_message = "Post has been updated!"


post_update_view = PostUpdateView.as_view()


class PostDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("posts:list")
    success_message = "Post has been deleted!"
    template_name = "posts/post_confirm_delete.html"


post_delete_view = PostDeleteView.as_view()


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"


post_detail_view = PostDetailView.as_view()


@login_required
def PostLikeView(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    post = get_object_or_404(Post, id=pk)
    user = request.user
    if post.likes.filter(id=user.id).exists():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return redirect("posts:list")


@login_required
def add_comment_view(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect("posts:detail", pk=pk)
    else:
        form = PostCommentForm()

    return render(request, "posts/postcomment_form.html", context={'form': form, 'post': post})

def category_list_view(request):
    categories = PostCategory.objects.all()
    return render(request, "posts/category_list.html", {"categories": categories})


def posts_by_category_view(request, category_id):
    category = get_object_or_404(PostCategory, pk=category_id)
    posts = Post.objects.filter(category=category).order_by("-created_datetime").select_related("user", "category")
    return render(request, "posts/posts_by_category.html", {"posts": posts, "category": category})

posts/templates/posts/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Categories{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'posts/css/categories.css' %}">
{% endblock %}

{% block content %}
<h1 class="mb-4">Choose category</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for category in categories %}
    <div class="col">
      <div class="card h-100 shadow-sm">
        <div class="card-body d-flex flex-column justify-content-center text-center">
          <h5 class="card-title">{{ category.name }}</h5>
          <a href="{% url 'posts:posts_by_category' category.id %}" class="btn btn-outline-primary mt-3">See posts</a>
        </div>
      </div>
    </div>
  {% empty %}
    <p class="text-muted">No categories to be displayed.</p>
  {% endfor %}
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Are you sure to delete this post? </h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-danger" value="Delete">
        <input type="reset" class="btn btn-secondary" value="Cancel">
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Details about post{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static "posts/css/post_detail.css" %}">
{% endblock %}


{% block content %}
    <div class="card">
                <div class="card-header post-title">
                    <div class="user-info">
                        <img src="{{ object.user.profile.image.url }}" class="account-img">
                        <h5>{{ object.user.username }}</h5>
                    </div>
                    {% if post.user == user %}
                        <div class="post-actions">
                            <a class="post-edit-icon" href="{% url "posts:edit" post.id %}"><i class="bi bi-pencil-square"></i></a>
                            <a class="post-delete-icon" href="{% url "posts:delete" post.id %}"><i class="bi bi-x-square"></i></a>
                        </div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p style="font-size: 12px;">Created: {{ post.created_datetime }}</p>
                    <p class="card-text">{{ post.contents|safe }}</p>
                </div>
                <div class="card-footer text-muted post-footer">
                    <div class="like-div">
                        <form action="{% url 'posts:like' post.id %}" method="POST">
                            {% csrf_token %}
                            {% if user in post.likes.all %}
                                <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-secondary"><i class="bi bi-hand-thumbs-up"> </i>Like</button>
                            {% else %}
                                <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-primary"><i class="bi bi-hand-thumbs-up"> </i>Like</button>
                            {% endif %}
                        </form>
                        <span class="text-secondary likes-number">Likes: {{ post.number_of_likes }}</span>
                    </div>
                    <div class="comment-div">
                        <a class="btn btn-primary" href="{% url "posts:add_comment" post.id %}"><i class="bi bi-chat-left-text-fill"></i> Add comment</a>
                    </div>
                </div>
                <br>
                <h6>Comments: </h6>
                {% for comment in post.postcomment_set.all %}
                    <p>{{ comment.user }}: {{ comment.contents }}</p>
                {% endfor %}
            </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}New post{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static "posts/css/post_form.css" %}">
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Create new post</legend>
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock %}

{% block additional_scripts %}
    {{ form.media }}
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts list{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'posts/css/posts_list.css' %}">
<link rel="stylesheet" href="{% static 'posts/css/sidebar.css' %}">
{% endblock %}

{% block content %}
<div class="main-layout">
  <!-- Left Sidebar: Search -->
  <aside class="left-sidebar">
    <h3>Search Posts</h3>
    <form method="GET" action="{% url 'posts:list' %}">
      <input
        type="text"
        name="q"
        placeholder="Search..."
        value="{{ search_query }}"
        autocomplete="off"
      />
      <button type="submit">Search</button>
    </form>
  </aside>

  <!-- Main Post List -->
  <div class="posts-list">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    {% endif %}

    <h1>Latest posts</h1>

    {% for post in object_list %}
      <div class="post-card">
        <div class="post-header">
          <div class="user-section">
            {% if post.user.profile.image %}
              <img src="{{ post.user.profile.image.url }}" alt="Profile Image" class="user-avatar" />
            {% else %}
              <img src="{% get_media_prefix %}profile_pics/avatar.jpg" alt="Default Image" class="user-avatar">
            {% endif %}
            <div>
              <h5>{{ post.user.username }}</h5>
              <p class="post-date">{{ post.created_datetime }}</p>
            </div>
          </div>

          {% if post.user == user %}
            <div class="post-actions">
              <a href="{% url 'posts:edit' post.id %}" title="Edytuj"><i class="bi bi-pencil-square"></i></a>
              <a href="{% url 'posts:delete' post.id %}" title="Usuń"><i class="bi bi-x-square"></i></a>
            </div>
          {% endif %}
        </div>

        <div class="post-body">
          <a href="{% url 'posts:detail' post.id %}">
            <h4>{{ post.title }}</h4>
            <p>{{ post.contents|safe }}</p>
          </a>
        </div>

        <div class="post-footer">
          <form action="{% url 'posts:like' post.id %}" method="POST">
            {% csrf_token %}
            <button
              type="submit"
              class="btn btn-sm {% if user in post.likes.all %}btn-secondary{% else %}btn-outline-primary{% endif %}"
            >
              <i class="bi bi-hand-thumbs-up"></i> Like
            </button>
            <span class="likes-count">({{ post.number_of_likes }})</span>
          </form>
          <a class="btn btn-sm btn-outline-info" href="{% url 'posts:add_comment' post.id %}">
            <i class="bi bi-chat-left-text"></i> Comment
          </a>
        </div>
      </div>
    {% empty %}
      <p>No posts found.</p>
    {% endfor %}

    <!-- Pagination -->
    <div class="pagination-container">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a
              class="page-link"
              href="?page={{ page_obj.previous_page_number }}&q={{ search_query }}"
              >&laquo;</a
            >
          </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}&q={{ search_query }}">
            {{ page_obj.number }}
          </a>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a
              class="page-link"
              href="?page={{ page_obj.next_page_number }}&q={{ search_query }}"
              >&raquo;</a
            >
          </li>
        {% endif %}
      </ul>
    </div>
  </div>

  <!-- Right Sidebar: Top 5 Most Liked Posts -->
  <aside class="right-sidebar">
    <h3>Top 5 Most Liked Posts</h3>
    <ul class="top-liked-posts">
      {% for top_post in top_liked_posts %}
        <li>
          <a href="{% url 'posts:detail' top_post.id %}">
            {{ top_post.title }} <span>({{ top_post.like_count }} 👍)</span>
          </a>
        </li>
      {% empty %}
        <li>No liked posts yet.</li>
      {% endfor %}
    </ul>
  </aside>
</div>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Edit">
    </form>
{% endblock %}

posts/templates/posts/postcomment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block stylesheets %}

<link rel="stylesheet" href="{% static 'posts/css/comment_form.css' %}">
{% endblock %}
{% block content %}

<div class="container mt-4">
    <div class="card shadow-sm rounded">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="mb-0">Dodaj komentarz</h5>
            {% if post %}
                <a href="{% url 'posts:detail' post.pk %}" class="btn btn-sm btn-outline-secondary">← Powrót do posta</a>
            {% endif %}
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success mt-2">Dodaj komentarz</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/posts_by_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts in category {{ category.name }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'posts/css/posts_list.css' %}">
<link rel="stylesheet" href="{% static 'posts/css/categories.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
  <div class="posts-list">
    <h1>Posts in category: {{ category.name }}</h1>

    {% for post in posts %}
      <div class="post-card">
        <div class="post-header">
          <div class="user-section">
            {% if post.user.profile.image.url %}
              <img src="{{ post.user.profile.image.url }}" alt="Profile Image" class="user-avatar">
            {% else %}
              <img src="{{ MEDIA_URL }}profile_pics/default.jpg" alt="Default Image" class="user-avatar">
            {% endif %}
            <div>
              <h5>{{ post.user.username }}</h5>
              <p class="post-date">{{ post.created_datetime }}</p>
            </div>
          </div>

          {% if post.user == user %}
            <div class="post-actions">
              <a href="{% url 'posts:edit' post.id %}" title="Edytuj"><i class="bi bi-pencil-square"></i></a>
              <a href="{% url 'posts:delete' post.id %}" title="Usuń"><i class="bi bi-x-square"></i></a>
            </div>
          {% endif %}
        </div>

        <div class="post-body">
          <a href="{% url 'posts:detail' post.id %}">
            <h4>{{ post.title }}</h4>
            <p>{{ post.contents|safe }}</p>
          </a>
        </div>

        <div class="post-footer">
          <form action="{% url 'posts:like' post.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm {% if user in post.likes.all %}btn-secondary{% else %}btn-outline-primary{% endif %}">
              <i class="bi bi-hand-thumbs-up"></i> Like
            </button>
            <span class="likes-count">({{ post.number_of_likes }})</span>
          </form>
          <a class="btn btn-sm btn-outline-info" href="{% url 'posts:add_comment' post.id %}">
            <i class="bi bi-chat-left-text"></i> Comment
          </a>
        </div>
      </div>
    {% empty %}
      <p>No posts in this category.</p>
    {% endfor %}
  </div>

  <aside class="sidebar">
    <h3>Category</h3>
    <p>{{ category.name }}</p>
  </aside>
</div>
{% endblock %}